### ISSUE TITLE
怎麼在brc-20上床架token的logo？

### ISSUE THREAD

**Issue by IM-Apple** [Next-DAO/brc20_indexer#1]
怎麼在brc-20上床架token的logo？
![Uploading image.png…]()
![16788868421](https://user-images.githubusercontent.com/118351523/225372835-61e5c05f-3803-4477-a58c-0c862d1718cf.png)

**Comment by shep-eth** [comment]
这个跟本项目无关，可以去 twitter 上联系 https://brc-20.io 的作者 https://twitter.com/Fukoshima1

**Comment by IM-Apple** [comment]
Thanks

shep.eth ***@***.***> 于2023年3月23日周四 23:45写道：
